language: python
python:
    - nightly
    - 3.6
    - 3.5
    - 3.4
    - 3.3
    - 2.7
install:
    - pip install -r requirements.txt
    - pip install .
    - pip install nose coveralls
script: 
    - coverage run --source=dissertate setup.py nosetests
after_success: coveralls
